server.port=${SERVER_PORT:8081}
spring.application.name=UniManage-BE
spring.main.banner-mode=console 
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/unimanage-db}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:9787}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# logging
logging.level.root=INFO
logging.level.com.example=DEBUG

# swagger
#springdoc.api-docs.enabled=true

# redis config
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6380}
# spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.jedis.pool.max-active=8
spring.data.redis.jedis.pool.max-idle=8
spring.data.redis.jedis.pool.min-idle=8

# Enable logging to see connection info
logging.level.org.springframework.data.redis=DEBUG
logging.level.io.lettuce.core=DEBUG

# DigitalOcean Spaces config
spaces.bucket=my-images
spaces.region=nyc3
spaces.endpoint=https://nyc3.digitaloceanspaces.com
spaces.access-key=YOUR_ACCESS_KEY
spaces.secret-key=YOUR_SECRET_KEY
# swagger config
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true