INSERT INTO departments (name)
VALUES ('Biology'),
       ('Chemistry'),
       ('Computer Science'),
       ('Environmental Science'),
       ('Mathematics'),
       ('Physics'),
       ('Geography'),
       ('History'),
       ('International Business Management'),
       ('Khmer Literature'),
       ('Linguistics'),
       ('Media and Communication'),
       ('Philosophy'),
       ('Psychology'),
       ('Sociology'),
       ('Social Work'),
       ('Tourism'),
       ('Automation & Supply Chain Systems Engineering'),
       ('Bioengineering'),
       ('Data Science Engineering'),
       ('Environmental Engineering'),
       ('Information Technology Engineering'),
       ('Telecommunication and Electronic Engineering'),
       ('Community Development'),
       ('Economic Development'),
       ('Natural Resources Management and Development'),
       ('Educational Studies'),
       ('Higher Education Development and Management'),
       ('Lifelong Learning'),
       ('Chinese'),
       ('English'),
       ('French'),
       ('Japanese'),
       ('Korean'),
       ('Thai'),
       ('International Relations'),
       ('International Economics'),
       ('Political Science and Public Policy'),
       ('Vietnamese Studies');
